### ISSUE TITLE
Idea: window menu function to change special window type to normal

### ISSUE THREAD

**Issue by tuomas2** [mjdenham/and-bible#31]
Now that there is multiple window support and links from a book/commentary are opened in a special window, it would be sometimes nice if user was able to change newly created special window to a normal window, such that links from that would create a new special window again.

This could be implemented as a new "Change window type to normal" function in window menu.

**Comment by Emet-like-AndBible** [comment]
There's another idea for a special window-because this window open links, and this window is not synchronized with other Windows (that is very well), then sometimes a desire appears a passage from the Bible, that was open in the special window, to synchronize with other open and active windows, id est, that open windows by the command from special window menu synchronized with the special window.

**Comment by tuomas2** [comment]
I think that window type change to 'normal' would do just this (if
synchronize feature is enabled).

2015-06-30 19:12 GMT+03:00 Emet-like-AndBible <notifications@github.com>:

> There's another idea for a special window-because this window open links,
> and this window is not synchronized with other Windows (that is very well),
> then sometimes a desire appears a passage from the Bible, that was open in
> the special window, to synchronize with other open and active windows, id
> est, that open windows by the command from special window menu synchronized
> with the special window.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mjdenham/and-bible/issues/31#issuecomment-117241243>.
>



-- 
T: Tuomas

**Comment by tuomas2** [comment]
I think this functionality is not really needed as it is always possible to "create new window" from special window, and then close special window. So closing this.
