### ISSUE TITLE
permissions question

### ISSUE THREAD

**Issue by radorn** [mjdenham/and-bible#77]
I'm curious about certain permissions this app requires.

The permissions the app asks for are the following:

1- read phone status and identity
2- modify or delete the contents of your SD card + read the contents of your SD card
3- full network access
4- modify system settings

I understand 2 and 3 are needed to download and manage resources (bibles, commentaries, dictionaries, maps...), but I don't see any need for 1 or 4.

Could you explain why you require that at all?

**Comment by radorn** [comment]
I see.
I guess there's no "just phone status" permission in Android or a similarly limited permission for settings.
It's always an all or nothing nonsense with these things.

Anyway, thank you for this marvelous Bible reader. God bless you.

**Comment by aharris88** [comment]
@mjdenham Is there a way to make those permissions optional? It would be nice if you could just install the app with the network access permission.

Then If you want to download a version offline on your SD card, it could ask for the SD card permission.

If you turn on the screen timeout setting, it could ask for that permission.

And if you turn on the setting to stop phone calls, them it could ask for that permission.

Is this possible?

**Comment by richpoore** [comment]
@aharris88 This is an offline Bible reader. I'm pretty sure andBible is offline.

**Comment by aharris88** [comment]
It might be nice if you could read online or offline, but that would be a separate issue.

As far as permissions goes, it could just install with the 2 permissions and ask for the other 2 if needed.

**Comment by mjdenham** [comment]
Dynamic runtime permission requests will need to be implemented when I start targeting Android 6.

And Bible will always need the SD Card permission as a key audience has only occasional internet access and it would be too complex to support online and offline modes.

Optionally enabling phone status identity sounds good in theory but the need is difficult to communicate to the user and if a call is answered while And Bible is speaking then the caller will hear And Bible speaking, which would require some explaining.  Before I implemented the stop-speak-on-call function a work colleague called while I was listening to an unusual OT passage!

I might be able to remove the permission to modify System Settings soon as IIRC it is not required to update screen sleep time on recent versions of Android, but I would need to check which versions.  Since I added this I have removed support for Android 2.2 and will soon remove support for 2.3, so I need to check  if this is still required.

**Comment by aharris88** [comment]
That makes sense. I didn't realize that the phone status permission was so that And Bible could pause reading out loud when a call comes in. I could see how that would be hard to communicate to the user. What about turn-by-turn navigation though? I have apps (like a podcast player) that pauses when you receive a call or when Google Maps says something during turn-by-turn navigation?

Also, I really appreciate you answering questions. I didn't want to install this app until I understood what the permissions were for.

I would also be interested in know who the key audience is, but that is unrelated to this issue.

**Comment by aharris88** [comment]
I added the permissions question to the [FAQ](https://github.com/mjdenham/and-bible/wiki/FAQ).

**Comment by mjdenham** [comment]
Thanks for adding to the FAQ!  Feel free to contribute to the wiki
